// <auto-generated />
namespace NewsApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version12));
        
        string IMigrationMetadata.Id
        {
            get { return "202107230519177_version 1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
